services:
  backend:
    build: .
    image: lineup:latest
    ports:
      - "8080:8080"
    networks:
      - back-tier
    depends_on:
      - database
    environment:
      - DB_URL=jdbc:postgresql://database:5432/lineup
  
  database: 
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lineup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - back-tier

volumes:
  pgdata:

networks:
  back-tier: