services:
  backend:
    build: .
    image: lineup-backend
    ports:
      - "8080:8080"
    networks:
      - back-tier
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:1234@database:5432/postgres
  
  database: 
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - back-tier

volumes:
  pgdata:

networks:
  back-tier: