spring.application.name=LineUp
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB

jwt.secret=vvjcvcjvcvcvcvkcvckvxvjxcvkxcjvqwewjxk
# jwt.secret=${JWT_SECRET}
jwt.expiration=36000

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=error
spring.jpa.open-in-view=false
files.UPLOAD_DIR=/uploads
springdoc.swagger-ui.path=/docs

STEAM_API_KEY = B8590EF052EA29FE85911C225F06542B

