spring.application.name=LineUp
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB


jwt.secret=TestJWTSecretasdmmkjkasjnaskdasdaskj
jwt.expiration=540000

server.key = "SERVER_KEY:csWW"

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=error
spring.jpa.open-in-view=false
files.UPLOAD_DIR=/uploads
springdoc.swagger-ui.path=/docs

STEAM_API_KEY = ${STEAM_API_KEY}

